### ISSUE TITLE
index_wiki

### ISSUE THREAD

**Issue by 731963709** [nealvaidya/xor-colbert-qa#1]
@nealvaidya Hi, your code is well written. But there is a problem bothering me.
Could you explain the data "the initial english-only wiki data" or give a link for me to get it ?

**Comment by nealvaidya** [comment]
Hi @731963709, you can find the instructions for how to generate the necessary tsv file [here](https://github.com/mia-workshop/MIA-Shared-Task-2022/tree/main/baseline/wikipedia_preprocess). In particular, we've only tested this with the english wikipedia data dumps, and the pretrained english colbert weights from [here](https://github.com/stanford-futuredata/ColBERT). I hope this helps!
